pipeline {
    agent any

    stages {
        stage('setup') {
         steps {
            browserstack(credentialsId: '3b3b64c0-5105-43e2-a083-28e2cfa9f98a') {
               bat 'mvn test'
            }
         }
      }
    post {
        always {
            cleanWs()
        }
    }
}
